# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dei' do
  pod 'AppCenter/Crashes', '~> 2.0.1'
  pod 'AppCenter/Analytics', '~> 2.0.1'
  pod 'AppCenterReactNativeShared', '~> 2.0.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  #pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

  platform :ios, '9.0'
end
